name: 'GH Actions - Release'

on:
  release:
    types:
      - created
      - edited

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Source tarballs only
          - FROM:     'ubuntu:focal'
            ARTIFACT_EXT: 'tar.[xb]z*'
          # only build one Deb File b/c they're so large
          - FROM:     'debian:buster'
            ARTIFACT_EXT: 'deb'
          - FROM:     'opensuse/leap:15.4'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'opensuse/leap:15.3'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'opensuse/leap:15.2'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:37'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:36'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:35'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'rockylinux:9.0'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'rockylinux:8.6'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'rockylinux:8.5'
            ARTIFACT_EXT: 'rpm'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: false

    - name: Extract tag name etc
      shell: bash
      run: |
        echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV
    - name: Test tag name etc
      run: |
        echo "${TAG_NAME}"
    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        COMPILER:   'clang'
        FLAGS:      ''
        MY_OS_NAME: linux
        IS_RELEASE: 1
      run: script/cibuild $FLAGS
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ARTIFACT_EXT: ${{ matrix.ARTIFACT_EXT }}
      with:
        args: "packages/*.${{ matrix.ARTIFACT_EXT }}"
