name: 'GH Actions - PR'

on: [ pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: true
      matrix:
        include:
          # only do one Deb file because they're so large
          - FROM:     'debian:bullseye'
          - FROM:     'opensuse/leap:15.5'
          - FROM:     'opensuse/leap:15.4'
          - FROM:     'fedora:40'
          - FROM:     'fedora:39'
          - FROM:     'fedora:38'
          - FROM:     'rockylinux:9.3'
          - FROM:     'manjarolinux/base'

    steps:
    - name: Checkout repository
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #v4.1.4
      with:
        fetch-depth: 2
        submodules: false

    # Ensure PRs are built against the PR Head
    # As opposed to the merge commit
    - name: Move to PR HEAD
      run: git checkout ${{ github.event.pull_request.head.sha }}

    - name: Extract short SHA
      shell: bash
      run: |
        echo "SHORT_SHA=`git rev-parse --short ${{ github.event.pull_request.head.sha }}`" >> $GITHUB_ENV
    - name: Test short SHA
      run: |
        echo "${SHORT_SHA}"

    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        COMPILER:   'clang'
        FLAGS:      ''
        MY_OS_NAME: linux
        IS_RELEASE: 0
      run: script/cibuild $FLAGS
