name: Windows-CI

on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os:              windows-2019
            is-release:      0
          - os:              windows-2022
            is-release:      0

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install CMake
        uses: lukka/get-cmake@5f6e04f5267c8133f1273bf2103583fc72c46b17 #v3.31.5
        with:
          cmakeVersion: 3.31.4

      - name: Build it
        run: script/build.ps1
